### ISSUE TITLE
Which SF1 rom binary?

### ISSUE THREAD

**Issue by seadra** [ShiningForceCentral/SF1DISASM#4]
What is the checksum information for the sf1.bin that needs to be used?

I tried using `Shining Force (U) [!].bin` with md5sum 4b4acbe75ff7aaeb534ab78ed95910d1 but the color palette seems to be all wrong, with a green SEGA logo and so on.

**Comment by xenometal** [comment]
The checksum for the ROM that you are using is correct.

**Comment by seadra** [comment]
Thanks for the confirmation! For some reason, dgen shows distorted colors but everything looks OK in KEGA Fusion.
